[PHP]
extension_dir = "D:/laragon/bin/php/php-8.4.16-nts-Win32-vs17-x64/ext"
max_execution_time=120
realpath_cache_size=4096K
realpath_cache_ttl=600
zend_extension=opcache
opcache.enable=1
opcache.enable_cli=1
opcache.revalidate_freq=0
extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

[mail function]
sendmail_path="D:/laragon/bin/mailpit/1.22.3/mailpit.exe sendmail"
